app:
  name: "Delayed Notifier"
  version: "1.0.0"

server:
  host: "notifier"
  port: 8081
  shutdown_timeout: 10s

db:
  postgres:
    host: ${DB_POSTGRES_HOST}
    port: 5432
    username: ${DB_POSTGRES_USERNAME}
    password: ${DB_POSTGRES_PASSWORD}
    database: ${DB_POSTGRES_DATABASE}
    max_open_conns: 0
    max_idle_conns: 2
    conn_max_lifetime: 0s

redis:
  host: "redis"
  port: 6379
  password: ""
  database: 0
  ttl: 1h

rabbitmq:
  client_conn:
    url: "amqp://guest:guest@rabbitmq:5672"
    timeout: 10s

logger:
  level: "info"

gin:
  mode: "release"

tg_bot:
  token: ${TG_BOT_TOKEN}

email:
  host: "smtp.gmail.com"           
  port: 587
  username: "${EMAIL_USERNAME}"                  
  password: "${EMAIL_PASSWORD}"                  
  from: "${EMAIL_FROM}" 