// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/notify": {
            "post": {
                "description": "Создание нового уведомления",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NOTIFICATIONS API"
                ],
                "summary": "Создание уведомления",
                "parameters": [
                    {
                        "description": "Данные для создания уведомления",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.CreateNotificationResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/notify/{id}": {
            "get": {
                "description": "Получение статуса конкретного уведомления",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NOTIFICATIONS API"
                ],
                "summary": "Получение статуса уведомления",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID уведомления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetNotificationStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Уведомление не найдено",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [],
                "description": "Удаление (отмена) существующего уведомления",
                "tags": [
                    "NOTIFICATIONS API"
                ],
                "summary": "Удаление (отмена) уведомления",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID уведомления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Уведомление не существует",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Ошибка бизнес логики",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Channel": {
            "type": "string",
            "enum": [
                "telegram",
                "email"
            ],
            "x-enum-varnames": [
                "ChannelTelegram",
                "ChannelEmail"
            ]
        },
        "models.Status": {
            "type": "string",
            "enum": [
                "scheduled",
                "sent",
                "cancelled",
                "failed"
            ],
            "x-enum-varnames": [
                "StatusScheduled",
                "StatusSent",
                "StatusCancelled",
                "StatusFailed"
            ]
        },
        "request.CreateNotificationRequest": {
            "type": "object",
            "required": [
                "channel",
                "message",
                "recipient",
                "scheduled_at"
            ],
            "properties": {
                "channel": {
                    "$ref": "#/definitions/models.Channel"
                },
                "message": {
                    "type": "string"
                },
                "recipient": {
                    "description": "тг или email",
                    "type": "string"
                },
                "scheduled_at": {
                    "type": "string"
                }
            }
        },
        "response.CreateNotificationResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "response.GetNotificationStatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/models.Status"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Delayed Notifier",
	Description:      "API for Delayed Notifier",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
