// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notify": {
            "post": {
                "description": "create notification with provided params",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notify"
                ],
                "summary": "create notification",
                "parameters": [
                    {
                        "description": "notification request",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateNotificationResponse"
                        }
                    },
                    "400": {
                        "description": "impossible to create notification",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to create notification",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notify/{notification_id}": {
            "get": {
                "description": "get notification status by notification_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notify"
                ],
                "summary": "get notification status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "notification ID",
                        "name": "notification_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetNotificationResponse"
                        }
                    },
                    "400": {
                        "description": "invalid notification_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to get notification status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "delete notification by notification_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notify"
                ],
                "summary": "delete notification",
                "parameters": [
                    {
                        "type": "string",
                        "description": "notification ID",
                        "name": "notification_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "delete notification successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid notification_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to delete notification",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateNotificationRequest": {
            "type": "object",
            "required": [
                "channel",
                "message",
                "recipient",
                "scheduled_at"
            ],
            "properties": {
                "channel": {
                    "enum": [
                        "email",
                        "telegram"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Channel"
                        }
                    ],
                    "example": "telegram"
                },
                "message": {
                    "type": "string",
                    "example": "test_message"
                },
                "recipient": {
                    "description": "адрес тг или email",
                    "type": "string",
                    "example": "796744183"
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2025-11-01T10:40:00Z"
                }
            }
        },
        "dto.CreateNotificationResponse": {
            "type": "object",
            "properties": {
                "notification_id": {
                    "type": "integer"
                }
            }
        },
        "dto.GetNotificationResponse": {
            "type": "object",
            "properties": {
                "notification_status": {
                    "$ref": "#/definitions/models.Status"
                }
            }
        },
        "models.Channel": {
            "type": "string",
            "enum": [
                "telegram",
                "email"
            ],
            "x-enum-varnames": [
                "ChannelTelegram",
                "ChannelEmail"
            ]
        },
        "models.Status": {
            "type": "string",
            "enum": [
                "scheduled",
                "sent",
                "cancelled",
                "failed"
            ],
            "x-enum-varnames": [
                "StatusScheduled",
                "StatusSent",
                "StatusCancelled",
                "StatusFailed"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Delayed Notifier",
	Description:      "API for Delayed Notifier",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
