basePath: /
definitions:
  models.Channel:
    enum:
    - telegram
    - email
    type: string
    x-enum-varnames:
    - ChannelTelegram
    - ChannelEmail
  models.Status:
    enum:
    - scheduled
    - sent
    - cancelled
    - failed
    type: string
    x-enum-varnames:
    - StatusScheduled
    - StatusSent
    - StatusCancelled
    - StatusFailed
  request.CreateNotificationRequest:
    properties:
      channel:
        $ref: '#/definitions/models.Channel'
      message:
        type: string
      recipient:
        description: тг или email
        type: string
      scheduled_at:
        type: string
    required:
    - channel
    - message
    - recipient
    - scheduled_at
    type: object
  response.CreateNotificationResponse:
    properties:
      id:
        type: integer
    type: object
  response.GetNotificationStatusResponse:
    properties:
      status:
        $ref: '#/definitions/models.Status'
    type: object
host: localhost:8081
info:
  contact: {}
  description: API for Delayed Notifier
  termsOfService: http://swagger.io/terms/
  title: Delayed Notifier
  version: "1.0"
paths:
  /api/v1/notify:
    post:
      consumes:
      - application/json
      description: Создание нового уведомления
      parameters:
      - description: Данные для создания уведомления
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.CreateNotificationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CreateNotificationResponse'
        "400":
          description: Ошибка валидации
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создание уведомления
      tags:
      - NOTIFICATIONS API
  /api/v1/notify/{id}:
    delete:
      description: Удаление (отмена) существующего уведомления
      parameters:
      - description: ID уведомления
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Ошибка валидации
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Уведомление не существует
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Ошибка бизнес логики
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      security: []
      summary: Удаление (отмена) уведомления
      tags:
      - NOTIFICATIONS API
    get:
      description: Получение статуса конкретного уведомления
      parameters:
      - description: ID уведомления
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetNotificationStatusResponse'
        "400":
          description: Ошибка валидации
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Уведомление не найдено
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получение статуса уведомления
      tags:
      - NOTIFICATIONS API
swagger: "2.0"
